apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  labels:
    app: opentelemetry-collector
spec:
  type: ClusterIP
  selector:
    app: opentelemetry-collector
  internalTrafficPolicy: Cluster
  ports:
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
