apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../base
  - ../../components/wif

patches:
  - target:
      kind: Deployment
      name: opentelemetry-collector
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: opentelemetry-collector
  - target:
      kind: HorizontalPodAutoscaler
      name: opentelemetry-collector
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: opentelemetry-collector
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: opentelemetry-collector
        namespace: opentelemetry
      spec:
        template:
          spec:
            containers:
              - name: opentelemetry-collector
                env:
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    value: /etc/gcp/credential-configuration.json
                volumeMounts:
                  - name: gcp-wif-config
                    mountPath: /etc/gcp
                    readOnly: true
                  - name: gcp-ksa-token
                    mountPath: /var/run/secrets/tokens
                    readOnly: true
            volumes:
              - name: gcp-wif-config
                configMap:
                  name: gcp-wif-config
              - name: gcp-ksa-token
                projected:
                  sources:
                    - serviceAccountToken:
                        path: gcp-ksa-token
                        expirationSeconds: 3600
                        audience: //iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL_ID}/providers/${PROVIDER_ID}
