# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry-collector
    app.kubernetes.io/component: daemonset
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: opentelemetry-collector
        app.kubernetes.io/component: daemonset
    spec:
      serviceAccountName: opentelemetry-collector
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: opentelemetry-collector
          imagePullPolicy: Always
          image: us-docker.pkg.dev/cloud-ops-agents-artifacts/google-cloud-opentelemetry-collector/otelcol-google:0.131.0
          args:
            - "--config=googlecontrolplane:xds://${CONTROL_PLANE_ADDRESS}?gcp.fleet_id=${FLEET_ID}&project=${OPTIONAL_PROJECT_ID}"
            - "--config=/conf/collector.yaml"
            - "--feature-gates=exporter.googlemanagedprometheus.intToDouble,receiver.prometheusreceiver.RemoveStartTimeAdjustment"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CONTROL_PLANE_ADDRESS
              value: "${CONTROL_PLANE_ADDRESS}"
            - name: FLEET_ID
              value: "${FLEET_ID}"
            - name: OPTIONAL_PROJECT_ID
              value: "${OPTIONAL_PROJECT_ID}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "${GOOGLE_APPLICATION_CREDENTIALS}"
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
          volumeMounts:
            - name: collector-config
              mountPath: /conf
            - name: gcp-wif-config
              mountPath: /etc/gcp
              readOnly: true
            - name: gcp-ksa-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlogdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 13133
      volumes:
        - name: collector-config
          configMap:
            name: collector-config
            items:
              - key: collector.yaml
                path: collector.yaml
        - name: gcp-wif-config
          configMap:
            name: gcp-wif-config
            optional: true
        - name: gcp-ksa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: gcp-ksa-token
                  expirationSeconds: 3600
                  audience: //iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL_ID}/providers/${PROVIDER_ID}
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlogdocker
          hostPath:
            path: /var/lib/docker/containers
