apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - 4_daemonset.yaml

patches:
  - target:
      kind: Deployment
      name: opentelemetry-collector
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: opentelemetry-collector
