apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      serviceAccountName: opentelemetry-collector
      securityContext:
        {}
      containers:
      - name: opentelemetry-collector
        imagePullPolicy: Always
        image: otel/opentelemetry-collector-contrib:0.99.0
        command:
          - "/otelcol-contrib"
          - "--config=/conf/collector.yaml"
        ports:
          - name: otlp-grpc
            containerPort: 4317
            protocol: TCP
          - name: otlp-http
            containerPort: 4318
            protocol: TCP
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        volumeMounts:
          - name: collector-config
            mountPath: /conf
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      volumes:
          - name: collector-config
            configMap:
              name: collector-config
              items:
              - key: collector.yaml
                path: collector.yaml
