apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: otel-collector
resources:
  - 0_namespace.yaml
  - 1_configmap.yaml
  - 2_rbac.yaml
  - 3_service.yaml
  - 4_deployment.yaml
